In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/diabetes.csv')

In [ ]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X=df.iloc[ :,:-1].values
y=df.iloc[ :,-1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [ ]:
X=sc.fit_transform(X)

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
# Build
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

# Compile
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.6016 - loss: 0.6565 - val_accuracy: 0.6623 - val_loss: 0.6159
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6205 - loss: 0.6299 - val_accuracy: 0.7078 - val_loss: 0.5832
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6948 - loss: 0.5749 - val_accuracy: 0.7273 - val_loss: 0.5593
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7408 - loss: 0.5320 - val_accuracy: 0.7468 - val_loss: 0.5426
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7226 - loss: 0.5486 - val_accuracy: 0.7727 - val_loss: 0.5304
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7714 - loss: 0.4898 - val_accuracy: 0.7792 - val_loss: 0.5223
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7193 - loss: 0.5202 - val_accuracy: 0.7922 - val_loss: 0.5151
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7265 - loss: 0.5230 - val_accuracy: 0.7987 - val_loss: 0.5102
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7705 - loss: 0.4785 - val_accuracy: 0.7857 - val_loss: 0.5052
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7195 - loss: 0.4958 - val_accuracy: 0.7987 - val_loss: 0.5004
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7544 - loss: 0.4831 - val_accuracy: 0.7987 - val_loss: 0.4950
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7519 - loss: 0.4854 - val_accuracy: 0.7922 - val_loss: 0.4919
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7754 - loss: 0.4513 - val_accuracy: 0.7987 - val_loss: 0.4885
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7680 - loss: 0.4703 - val_accuracy: 0.8117 - val_loss: 0.4858
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7942 - loss: 0.4259 - val_accuracy: 0.8052 - val_loss: 0.4845
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7705 - loss: 0.4423 - val_accuracy: 0.8052 - val_loss: 0.4831
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.4578 - val_accuracy: 0.7987 - val_loss: 0.4828
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7531 - loss: 0.4592 - val_accuracy: 0.8052 - val_loss: 0.4800
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7379 - loss: 0.4888 - val_accuracy: 0.8117 - val_loss: 0.4789
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7691 - loss: 0.4559 - val_accuracy: 0.8117 - val_loss: 0.4777
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7446 - loss: 0.4651 - val_accuracy: 0.8117 - val_loss: 0.4762
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7438 - loss: 0.4653 - val_accuracy: 0.7987 - val_loss: 0.4774
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7547 - loss: 0.4665 - val_accuracy: 0.8052 - val_loss: 0.4765
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7455 - loss: 0.4709 - val_accuracy: 0.8052 - val_loss: 0.4757
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7788 - loss: 0.4439 - val_accuracy: 0.7987 - val_loss: 0.4762
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7631 - loss: 0.4611 - val_accuracy: 0.8052 - val_loss: 0.4755
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7584 - loss: 0.4793 - val_accuracy: 0.8117 - val_loss: 0.4754
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7756 - loss: 0.4477 - val_accuracy: 0.8052 - val_loss: 0.4744
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7561 - loss: 0.4695 - val_accuracy: 0.8052 - val_loss: 0.4734
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7683 - loss: 0.4604 - val_accuracy: 0.8052 - val_loss: 0.4740
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7737 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4736
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7894 - loss: 0.4317 - val_accuracy: 0.8052 - val_loss: 0.4742
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7894 - loss: 0.4307 - val_accuracy: 0.8052 - val_loss: 0.4732
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7865 - loss: 0.4223 - val_accuracy: 0.8052 - val_loss: 0.4723
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7573 - loss: 0.4555 - val_accuracy: 0.8052 - val_loss: 0.4733
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7703 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4737
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7800 - loss: 0.4477 - val_accuracy: 0.8052 - val_loss: 0.4731
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7447 - loss: 0.4818 - val_accuracy: 0.7987 - val_loss: 0.4726
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7635 - loss: 0.4423 - val_accuracy: 0.7987 - val_loss: 0.4729
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7844 - loss: 0.4496 - val_accuracy: 0.7987 - val_loss: 0.4725
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7723 - loss: 0.4570 - val_accuracy: 0.7987 - val_loss: 0.4720
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7831 - loss: 0.4541 - val_accuracy: 0.7922 - val_loss: 0.4715
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7880 - loss: 0.4263 - val_accuracy: 0.7987 - val_loss: 0.4702
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7827 - loss: 0.4483 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7393 - loss: 0.4903 - val_accuracy: 0.8052 - val_loss: 0.4689
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7933 - loss: 0.4259 - val_accuracy: 0.8052 - val_loss: 0.4692
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4226 - val_accuracy: 0.8117 - val_loss: 0.4688
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7728 - loss: 0.4560 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7877 - loss: 0.4260 - val_accuracy: 0.8052 - val_loss: 0.4691
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.4317 - val_accuracy: 0.8052 - val_loss: 0.4692

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.6 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):

    model = Sequential()

    model.add(Dense(32, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])

    model.compile(optimizer=optimizer,
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

tuner.search(X_train, y_train, epochs=5,
             validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 10s

In [ ]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
optimizer: adam
Score: 0.8246753215789795

Trial 3 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7727272510528564

Trial 1 summary
Hyperparameters:
optimizer: sgd
Score: 0.7402597665786743

Trial 2 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5844155550003052

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, y_train,
          batch_size=32,
          epochs=100,
          initial_epoch=6,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7609 - loss: 0.5315 - val_accuracy: 0.7922 - val_loss: 0.4995
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7676 - loss: 0.5119 - val_accuracy: 0.8052 - val_loss: 0.4859
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7531 - loss: 0.5217 - val_accuracy: 0.8052 - val_loss: 0.4750
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8011 - loss: 0.4857 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8104 - loss: 0.4748 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7742 - loss: 0.4842 - val_accuracy: 0.7987 - val_loss: 0.4556
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7763 - loss: 0.4761 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7661 - loss: 0.4745 - val_accuracy: 0.7987 - val_loss: 0.4491
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7621 - loss: 0.4809 - val_accuracy: 0.7922 - val_loss: 0.4483
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4792 - val_accuracy: 0.7922 - val_loss: 0.4464
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7757 - loss: 0.4490 - val_accuracy: 0.7987 - val_loss: 0.4477
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7795 - loss: 0.4616 - val_accuracy: 0.7922 - val_loss: 0.4460
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7636 - loss: 0.4627 - val_accuracy: 0.7922 - val_loss: 0.4465
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7770 - loss: 0.4596 - val_accuracy: 0.7857 - val_loss: 0.4464
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7863 - loss: 0.4539 - val_accuracy: 0.7857 - val_loss: 0.4453
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7644 - loss: 0.4541 - val_accuracy: 0.7857 - val_loss: 0.4448
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7797 - loss: 0.4421 - val_accuracy: 0.7922 - val_loss: 0.4450
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8033 - loss: 0.4283 - val_accuracy: 0.7922 - val_loss: 0.4462
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7931 - loss: 0.4435 - val_accuracy: 0.7922 - val_loss: 0.4459
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7371 - loss: 0.4794 - val_accuracy: 0.7922 - val_loss: 0.4466
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7698 - loss: 0.4629 - val_accuracy: 0.7922 - val_loss: 0.4470
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7625 - loss: 0.4719 - val_accuracy: 0.7922 - val_loss: 0.4463
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7848 - loss: 0.4523 - val_accuracy: 0.7922 - val_loss: 0.4464
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7986 - loss: 0.4210 - val_accuracy: 0.7922 - val_loss: 0.4457
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4192 - val_accuracy: 0.7922 - val_loss: 0.4469
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4680 - val_accuracy: 0.7922 - val_loss: 0.4475
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7746 - loss: 0.4554 - val_accuracy: 0.7987 - val_loss: 0.4471
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7679 - loss: 0.4500 - val_accuracy: 0.7922 - val_loss: 0.4472
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.4287 - val_accuracy: 0.8052 - val_loss: 0.4472
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7787 - loss: 0.4631 - val_accuracy: 0.8052 - val_loss: 0.4479
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7900 - loss: 0.4330 - val_accuracy: 0.8052 - val_loss: 0.4494
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7669 - loss: 0.4494 - val_accuracy: 0.8052 - val_loss: 0.4487
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7816 - loss: 0.4517 - val_accuracy: 0.8052 - val_loss: 0.4493
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7814 - loss: 0.4508 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7743 - loss: 0.4471 - val_accuracy: 0.7922 - val_loss: 0.4493
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7758 - loss: 0.4313 - val_accuracy: 0.8052 - val_loss: 0.4494
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7814 - loss: 0.4736 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7872 - loss: 0.4220 - val_accuracy: 0.7922 - val_loss: 0.4525
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7645 - loss: 0.4750 - val_accuracy: 0.7922 - val_loss: 0.4521
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7772 - loss: 0.4398 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7978 - loss: 0.4158 - val_accuracy: 0.7987 - val_loss: 0.4503
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7767 - loss: 0.4563 - val_accuracy: 0.7922 - val_loss: 0.4503
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7800 - loss: 0.4324 - val_accuracy: 0.8052 - val_loss: 0.4512
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7881 - loss: 0.4370 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7770 - loss: 0.4495 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7803 - loss: 0.4564 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7829 - loss: 0.4464 - val_accuracy: 0.7922 - val_loss: 0.4539
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8114 - loss: 0.4186 - val_accuracy: 0.7922 - val_loss: 0.4535
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8015 - loss: 0.4233 - val_accuracy: 0.7987 - val_loss: 0.4526
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7912 - loss: 0.4259 - val_accuracy: 0.7922 - val_loss: 0.4535
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4199 - val_accuracy: 0.7922 - val_loss: 0.4543
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4093 - val_accuracy: 0.7987 - val_loss: 0.4555
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8035 - loss: 0.4045 - val_accuracy: 0.7987 - val_loss: 0.4555
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8116 - loss: 0.4087 - val_accuracy: 0.8052 - val_loss: 0.4558
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8291 - loss: 0.3875 - val_accuracy: 0.8052 - val_loss: 0.4553
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7985 - loss: 0.4176 - val_accuracy: 0.7987 - val_loss: 0.4562
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4200 - val_accuracy: 0.7922 - val_loss: 0.4570
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7921 - loss: 0.4310 - val_accuracy: 0.7857 - val_loss: 0.4577
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4334 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7977 - loss: 0.4096 - val_accuracy: 0.7922 - val_loss: 0.4561
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7927 - loss: 0.4283 - val_accuracy: 0.7857 - val_loss: 0.4576
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7768 - loss: 0.4269 - val_accuracy: 0.7922 - val_loss: 0.4566
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7868 - loss: 0.4272 - val_accuracy: 0.7987 - val_loss: 0.4568
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7981 - loss: 0.4328 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8067 - loss: 0.4053 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7758 - loss: 0.4380 - val_accuracy: 0.7792 - val_loss: 0.4566
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8043 - loss: 0.4148 - val_accuracy: 0.7922 - val_loss: 0.4564
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7737 - loss: 0.4277 - val_accuracy: 0.7857 - val_loss: 0.4584
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.3956 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4226 - val_accuracy: 0.7857 - val_loss: 0.4599
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8033 - loss: 0.4195 - val_accuracy: 0.7857 - val_loss: 0.4611
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8019 - loss: 0.4292 - val_accuracy: 0.7857 - val_loss: 0.4615
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8288 - loss: 0.3851 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8057 - loss: 0.3961 - val_accuracy: 0.7792 - val_loss: 0.4626
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8165 - loss: 0.4033 - val_accuracy: 0.7857 - val_loss: 0.4625
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8100 - loss: 0.4019 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8000 - loss: 0.4162 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7784 - loss: 0.4444 - val_accuracy: 0.7857 - val_loss: 0.4619
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8145 - loss: 0.3858 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4287 - val_accuracy: 0.7922 - val_loss: 0.4628
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8115 - loss: 0.4029 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8119 - loss: 0.4154 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8095 - loss: 0.4184 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7880 - loss: 0.4247 - val_accuracy: 0.7922 - val_loss: 0.4602
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7826 - loss: 0.4493 - val_accuracy: 0.7857 - val_loss: 0.4614
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7983 - loss: 0.4132 - val_accuracy: 0.7857 - val_loss: 0.4611
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8057 - loss: 0.4132 - val_accuracy: 0.7792 - val_loss: 0.4601
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8001 - loss: 0.4069 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.4052 - val_accuracy: 0.7792 - val_loss: 0.4597
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7996 - loss: 0.4292 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7911 - loss: 0.4427 - val_accuracy: 0.7987 - val_loss: 0.4635
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4133 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4209 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7905 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4627

In [ ]:
def build_model(hp):

    model = Sequential()

    units = hp.Int('units', min_value=8, max_value=128, step=8)

    model.add(Dense(units=units, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory ='mydir')

tuner.search(X_train, y_train, epochs=5,
             validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 13s

In [ ]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
units: 88
Score: 0.8051947951316833

Trial 0 summary
Hyperparameters:
units: 64
Score: 0.7857142686843872

Trial 3 summary
Hyperparameters:
units: 120
Score: 0.7792207598686218

Trial 1 summary
Hyperparameters:
units: 56
Score: 0.7727272510528564

Trial 4 summary
Hyperparameters:
units: 24
Score: 0.7467532753944397

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 88}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 88)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            89 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 881 (3.44 KB)

 Trainable params: 881 (3.44 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, y_train,
          batch_size=32,
          epochs=100,
          initial_epoch=6,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7697 - loss: 0.5054 - val_accuracy: 0.7792 - val_loss: 0.4740
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7624 - loss: 0.4927 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7648 - loss: 0.4936 - val_accuracy: 0.7987 - val_loss: 0.4602
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7882 - loss: 0.4442 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7956 - loss: 0.4456 - val_accuracy: 0.7922 - val_loss: 0.4552
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4378 - val_accuracy: 0.7922 - val_loss: 0.4547
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7574 - loss: 0.4762 - val_accuracy: 0.7922 - val_loss: 0.4544
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7599 - loss: 0.4659 - val_accuracy: 0.7922 - val_loss: 0.4528
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7832 - loss: 0.4474 - val_accuracy: 0.7987 - val_loss: 0.4520
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8221 - loss: 0.4111 - val_accuracy: 0.7987 - val_loss: 0.4528
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7631 - loss: 0.4669 - val_accuracy: 0.7987 - val_loss: 0.4529
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7760 - loss: 0.4549 - val_accuracy: 0.8052 - val_loss: 0.4514
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7796 - loss: 0.4441 - val_accuracy: 0.7987 - val_loss: 0.4515
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7561 - loss: 0.4874 - val_accuracy: 0.7987 - val_loss: 0.4507
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7886 - loss: 0.4425 - val_accuracy: 0.7987 - val_loss: 0.4520
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4172 - val_accuracy: 0.8117 - val_loss: 0.4544
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7844 - loss: 0.4240 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7791 - loss: 0.4245 - val_accuracy: 0.8052 - val_loss: 0.4524
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7844 - loss: 0.4319 - val_accuracy: 0.8182 - val_loss: 0.4524
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7783 - loss: 0.4461 - val_accuracy: 0.8247 - val_loss: 0.4518
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7978 - loss: 0.4243 - val_accuracy: 0.8182 - val_loss: 0.4518
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4473 - val_accuracy: 0.8117 - val_loss: 0.4526
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4280 - val_accuracy: 0.8182 - val_loss: 0.4517
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7437 - loss: 0.4714 - val_accuracy: 0.8182 - val_loss: 0.4514
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7685 - loss: 0.4434 - val_accuracy: 0.8182 - val_loss: 0.4543
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7827 - loss: 0.4420 - val_accuracy: 0.8247 - val_loss: 0.4542
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7913 - loss: 0.4315 - val_accuracy: 0.8117 - val_loss: 0.4550
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7897 - loss: 0.4055 - val_accuracy: 0.8117 - val_loss: 0.4546
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4231 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7929 - loss: 0.4201 - val_accuracy: 0.8117 - val_loss: 0.4539
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7783 - loss: 0.4480 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7926 - loss: 0.4078 - val_accuracy: 0.8117 - val_loss: 0.4550
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7814 - loss: 0.4356 - val_accuracy: 0.8117 - val_loss: 0.4552
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7928 - loss: 0.4139 - val_accuracy: 0.8182 - val_loss: 0.4527
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7832 - loss: 0.4350 - val_accuracy: 0.8117 - val_loss: 0.4530
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7972 - loss: 0.4162 - val_accuracy: 0.8117 - val_loss: 0.4538
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7684 - loss: 0.4373 - val_accuracy: 0.8117 - val_loss: 0.4542
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7788 - loss: 0.4335 - val_accuracy: 0.8182 - val_loss: 0.4538
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7755 - loss: 0.4309 - val_accuracy: 0.8182 - val_loss: 0.4551
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4344 - val_accuracy: 0.8247 - val_loss: 0.4549
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8032 - loss: 0.3977 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8101 - loss: 0.4175 - val_accuracy: 0.8117 - val_loss: 0.4549
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7723 - loss: 0.4314 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8214 - loss: 0.4031 - val_accuracy: 0.8117 - val_loss: 0.4555
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7975 - loss: 0.4200 - val_accuracy: 0.8182 - val_loss: 0.4538
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7634 - loss: 0.4469 - val_accuracy: 0.8117 - val_loss: 0.4554
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8099 - loss: 0.4188 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8022 - loss: 0.4236 - val_accuracy: 0.8182 - val_loss: 0.4546
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8097 - loss: 0.4083 - val_accuracy: 0.8182 - val_loss: 0.4539
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7972 - loss: 0.4247 - val_accuracy: 0.8182 - val_loss: 0.4530
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7944 - loss: 0.4251 - val_accuracy: 0.8182 - val_loss: 0.4526
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.3980 - val_accuracy: 0.8117 - val_loss: 0.4536
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7799 - loss: 0.4321 - val_accuracy: 0.7987 - val_loss: 0.4549
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.4074 - val_accuracy: 0.8052 - val_loss: 0.4535
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8145 - loss: 0.4006 - val_accuracy: 0.8117 - val_loss: 0.4536
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4309 - val_accuracy: 0.7987 - val_loss: 0.4545
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.4194 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8044 - loss: 0.4380 - val_accuracy: 0.8052 - val_loss: 0.4551
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8085 - loss: 0.4113 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3844 - val_accuracy: 0.8117 - val_loss: 0.4538
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4135 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8092 - loss: 0.4021 - val_accuracy: 0.8247 - val_loss: 0.4548
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8223 - loss: 0.3889 - val_accuracy: 0.8117 - val_loss: 0.4553
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7956 - loss: 0.4110 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8218 - loss: 0.4084 - val_accuracy: 0.8247 - val_loss: 0.4570
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7911 - loss: 0.4309 - val_accuracy: 0.8182 - val_loss: 0.4568
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7962 - loss: 0.4360 - val_accuracy: 0.8182 - val_loss: 0.4558
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8126 - loss: 0.4088 - val_accuracy: 0.8312 - val_loss: 0.4573
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8034 - loss: 0.4312 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8090 - loss: 0.3909 - val_accuracy: 0.8182 - val_loss: 0.4543
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8251 - loss: 0.4075 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8258 - loss: 0.3953 - val_accuracy: 0.8117 - val_loss: 0.4537
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8337 - loss: 0.3883 - val_accuracy: 0.8182 - val_loss: 0.4550
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8342 - loss: 0.3809 - val_accuracy: 0.8182 - val_loss: 0.4539
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8148 - loss: 0.4188 - val_accuracy: 0.8247 - val_loss: 0.4550
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8313 - loss: 0.3942 - val_accuracy: 0.8377 - val_loss: 0.4547
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8010 - loss: 0.4299 - val_accuracy: 0.8312 - val_loss: 0.4544
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8203 - loss: 0.3851 - val_accuracy: 0.8117 - val_loss: 0.4539
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8320 - loss: 0.3863 - val_accuracy: 0.8117 - val_loss: 0.4528
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8358 - loss: 0.3906 - val_accuracy: 0.8182 - val_loss: 0.4522
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8149 - loss: 0.3915 - val_accuracy: 0.8117 - val_loss: 0.4529
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8294 - loss: 0.3890 - val_accuracy: 0.8117 - val_loss: 0.4547
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4095 - val_accuracy: 0.8182 - val_loss: 0.4544
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7998 - loss: 0.3981 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8246 - loss: 0.4032 - val_accuracy: 0.8117 - val_loss: 0.4565
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8183 - loss: 0.3987 - val_accuracy: 0.8182 - val_loss: 0.4576
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8122 - loss: 0.4054 - val_accuracy: 0.8247 - val_loss: 0.4572
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3809 - val_accuracy: 0.8182 - val_loss: 0.4570
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8275 - loss: 0.3803 - val_accuracy: 0.8182 - val_loss: 0.4570
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.3988 - val_accuracy: 0.8052 - val_loss: 0.4567
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8145 - loss: 0.4035 - val_accuracy: 0.8182 - val_loss: 0.4575
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8345 - loss: 0.3907 - val_accuracy: 0.8182 - val_loss: 0.4581
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8096 - loss: 0.4143 - val_accuracy: 0.8117 - val_loss: 0.4572
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8098 - loss: 0.4148 - val_accuracy: 0.8117 - val_loss: 0.4559

In [ ]:
def build_model(hp):

    model = Sequential()

    model.add(Dense(72, activation='relu', input_dim=8))

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        model.add(Dense(72, activation='relu'))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    return model

In [ ]:

tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='layers')

In [ ]:
tuner.search(X_train, y_train, epochs=5,
             validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 11s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train, y_train,
          batch_size=32,
          epochs=100,
          initial_epoch=6,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7657 - loss: 0.4863 - val_accuracy: 0.8052 - val_loss: 0.4801
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7579 - loss: 0.4769 - val_accuracy: 0.8117 - val_loss: 0.4757
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7890 - loss: 0.4377 - val_accuracy: 0.8117 - val_loss: 0.4742
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8112 - loss: 0.4297 - val_accuracy: 0.8052 - val_loss: 0.4817
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7929 - loss: 0.4446 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7938 - loss: 0.4393 - val_accuracy: 0.8117 - val_loss: 0.4935
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7580 - loss: 0.4479 - val_accuracy: 0.7922 - val_loss: 0.4750
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8196 - loss: 0.4077 - val_accuracy: 0.7857 - val_loss: 0.4723
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7889 - loss: 0.4284 - val_accuracy: 0.7727 - val_loss: 0.4814
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7815 - loss: 0.4133 - val_accuracy: 0.7922 - val_loss: 0.4820
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4114 - val_accuracy: 0.7987 - val_loss: 0.4836
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7828 - loss: 0.4257 - val_accuracy: 0.7792 - val_loss: 0.4698
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4111 - val_accuracy: 0.7922 - val_loss: 0.4724
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8057 - loss: 0.3915 - val_accuracy: 0.7922 - val_loss: 0.4828
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8135 - loss: 0.3961 - val_accuracy: 0.8052 - val_loss: 0.4824
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8043 - loss: 0.3776 - val_accuracy: 0.7922 - val_loss: 0.4771
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8238 - loss: 0.3769 - val_accuracy: 0.7792 - val_loss: 0.4854
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8377 - loss: 0.3515 - val_accuracy: 0.7727 - val_loss: 0.4752
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8439 - loss: 0.3435 - val_accuracy: 0.7987 - val_loss: 0.4854
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3747 - val_accuracy: 0.7727 - val_loss: 0.4869
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8306 - loss: 0.3726 - val_accuracy: 0.7857 - val_loss: 0.5027
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3736 - val_accuracy: 0.7662 - val_loss: 0.5026
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8541 - loss: 0.3320 - val_accuracy: 0.7857 - val_loss: 0.4853
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8319 - loss: 0.3787 - val_accuracy: 0.7727 - val_loss: 0.5124
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8445 - loss: 0.3655 - val_accuracy: 0.7727 - val_loss: 0.5168
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8631 - loss: 0.3193 - val_accuracy: 0.7857 - val_loss: 0.4953
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8451 - loss: 0.3533 - val_accuracy: 0.7857 - val_loss: 0.4946
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8664 - loss: 0.3280 - val_accuracy: 0.7922 - val_loss: 0.5037
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8661 - loss: 0.3101 - val_accuracy: 0.7922 - val_loss: 0.5059
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8449 - loss: 0.3369 - val_accuracy: 0.7857 - val_loss: 0.5159
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8635 - loss: 0.3136 - val_accuracy: 0.7987 - val_loss: 0.5214
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8815 - loss: 0.3004 - val_accuracy: 0.7792 - val_loss: 0.5092
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8821 - loss: 0.3015 - val_accuracy: 0.7597 - val_loss: 0.5587
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.3044 - val_accuracy: 0.7857 - val_loss: 0.5501
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8951 - loss: 0.2909 - val_accuracy: 0.7792 - val_loss: 0.5354
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8801 - loss: 0.2842 - val_accuracy: 0.7987 - val_loss: 0.5492
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8988 - loss: 0.2838 - val_accuracy: 0.7468 - val_loss: 0.5722
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8822 - loss: 0.2856 - val_accuracy: 0.7727 - val_loss: 0.5652
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8830 - loss: 0.2837 - val_accuracy: 0.7727 - val_loss: 0.5601
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8777 - loss: 0.2715 - val_accuracy: 0.7857 - val_loss: 0.5564
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.2909 - val_accuracy: 0.7792 - val_loss: 0.5976
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9038 - loss: 0.2365 - val_accuracy: 0.7857 - val_loss: 0.5717
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9044 - loss: 0.2537 - val_accuracy: 0.7727 - val_loss: 0.5533
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8953 - loss: 0.2546 - val_accuracy: 0.7143 - val_loss: 0.6269
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8966 - loss: 0.2706 - val_accuracy: 0.7727 - val_loss: 0.6088
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.2476 - val_accuracy: 0.7662 - val_loss: 0.6264
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9068 - loss: 0.2466 - val_accuracy: 0.7792 - val_loss: 0.6115
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9210 - loss: 0.2341 - val_accuracy: 0.7468 - val_loss: 0.6350
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9206 - loss: 0.2232 - val_accuracy: 0.7338 - val_loss: 0.6239
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9155 - loss: 0.2275 - val_accuracy: 0.7727 - val_loss: 0.6476
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8928 - loss: 0.2346 - val_accuracy: 0.7662 - val_loss: 0.6376
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9159 - loss: 0.2396 - val_accuracy: 0.7727 - val_loss: 0.6474
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9211 - loss: 0.2160 - val_accuracy: 0.7403 - val_loss: 0.6620
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9167 - loss: 0.2032 - val_accuracy: 0.7208 - val_loss: 0.7025
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9295 - loss: 0.2123 - val_accuracy: 0.7792 - val_loss: 0.6500
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9165 - loss: 0.2286 - val_accuracy: 0.7857 - val_loss: 0.7035
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9248 - loss: 0.2049 - val_accuracy: 0.7727 - val_loss: 0.6932
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9255 - loss: 0.2089 - val_accuracy: 0.7662 - val_loss: 0.6760
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9492 - loss: 0.1649 - val_accuracy: 0.7662 - val_loss: 0.7052
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9347 - loss: 0.1837 - val_accuracy: 0.7597 - val_loss: 0.8155
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9297 - loss: 0.1983 - val_accuracy: 0.7468 - val_loss: 0.7423
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9485 - loss: 0.1818 - val_accuracy: 0.7792 - val_loss: 0.7201
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9299 - loss: 0.1974 - val_accuracy: 0.7597 - val_loss: 0.7250
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9513 - loss: 0.1735 - val_accuracy: 0.7792 - val_loss: 0.7396
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9257 - loss: 0.1690 - val_accuracy: 0.7468 - val_loss: 0.7230
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9548 - loss: 0.1540 - val_accuracy: 0.7403 - val_loss: 0.7168
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9570 - loss: 0.1511 - val_accuracy: 0.7792 - val_loss: 0.7071
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9623 - loss: 0.1426 - val_accuracy: 0.7727 - val_loss: 0.7532
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9478 - loss: 0.1548 - val_accuracy: 0.7403 - val_loss: 0.7242
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9587 - loss: 0.1392 - val_accuracy: 0.7532 - val_loss: 0.8154
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9452 - loss: 0.1577 - val_accuracy: 0.7662 - val_loss: 0.8093
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9598 - loss: 0.1300 - val_accuracy: 0.7338 - val_loss: 0.8511
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9477 - loss: 0.1490 - val_accuracy: 0.7532 - val_loss: 0.7904
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9521 - loss: 0.1246 - val_accuracy: 0.7403 - val_loss: 0.8241
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9639 - loss: 0.1386 - val_accuracy: 0.7468 - val_loss: 0.8175
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9787 - loss: 0.1066 - val_accuracy: 0.7662 - val_loss: 0.8775
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9400 - loss: 0.1400 - val_accuracy: 0.7532 - val_loss: 0.8272
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9678 - loss: 0.1134 - val_accuracy: 0.7338 - val_loss: 0.9279
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9572 - loss: 0.1293 - val_accuracy: 0.7338 - val_loss: 0.8653
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9815 - loss: 0.0985 - val_accuracy: 0.7273 - val_loss: 0.9316
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9668 - loss: 0.1191 - val_accuracy: 0.7403 - val_loss: 0.8493
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9808 - loss: 0.0924 - val_accuracy: 0.7403 - val_loss: 0.9213
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9808 - loss: 0.0876 - val_accuracy: 0.7403 - val_loss: 0.9270
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9793 - loss: 0.0917 - val_accuracy: 0.7338 - val_loss: 0.9662
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9659 - loss: 0.0973 - val_accuracy: 0.7143 - val_loss: 0.9939
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9673 - loss: 0.1121 - val_accuracy: 0.7662 - val_loss: 0.9882
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9730 - loss: 0.0937 - val_accuracy: 0.7403 - val_loss: 0.9206
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0886 - val_accuracy: 0.7403 - val_loss: 1.0591
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9733 - loss: 0.0922 - val_accuracy: 0.7273 - val_loss: 1.0529
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9724 - loss: 0.0856 - val_accuracy: 0.7403 - val_loss: 1.0130
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9799 - loss: 0.0755 - val_accuracy: 0.7208 - val_loss: 1.0161
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9850 - loss: 0.0720 - val_accuracy: 0.7208 - val_loss: 1.0808
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9893 - loss: 0.0574 - val_accuracy: 0.7338 - val_loss: 1.0414
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9806 - loss: 0.0752 - val_accuracy: 0.7403 - val_loss: 1.0210

In [ ]:
def build_model(hp):

    model = Sequential()

    counter = 0

    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

        if counter == 0:
            model.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i),
                                         values=['relu', 'tanh', 'sigmoid']),
                    input_dim=8
                )
            )
            model.add(
    Dropout(
        hp.Choice('dropout' + str(i),
                  values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
    )
)
        else:
            model.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i),
                                         values=['relu', 'tanh', 'sigmoid'])
                )
            )
            model.add(
    Dropout(
        hp.Choice('dropout' + str(i),
                  values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
    )
)
        counter += 1

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=hp.Choice('optimizer',
                            values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory="mydir",
    project_name='final'
)

In [ ]:
tuner.search(X_train, y_train, epochs=5,
             validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 13s

In [ ]:
tuner.results_summary()

Results summary
Results in mydir/final
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 1 summary
Hyperparameters:
num_layers: 2
units0: 64
activation0: tanh
dropout0: 0.7
optimizer: rmsprop
units1: 56
activation1: tanh
dropout1: 0.5
units2: 64
activation2: relu
dropout2: 0.6
units3: 120
activation3: tanh
dropout3: 0.4
units4: 48
activation4: relu
dropout4: 0.2
units5: 96
activation5: tanh
dropout5: 0.8
units6: 88
activation6: tanh
dropout6: 0.2
units7: 96
activation7: relu
dropout7: 0.9
Score: 0.7857142686843872

Trial 0 summary
Hyperparameters:
num_layers: 8
units0: 48
activation0: relu
dropout0: 0.2
optimizer: adam
units1: 8
activation1: relu
dropout1: 0.1
units2: 8
activation2: relu
dropout2: 0.1
units3: 8
activation3: relu
dropout3: 0.1
units4: 8
activation4: relu
dropout4: 0.1
units5: 8
activation5: relu
dropout5: 0.1
units6: 8
activation6: relu
dropout6: 0.1
units7: 8
activation7: relu
dropout7: 0.1
Score: 0.7467532753944397

Trial 2 summary
Hyperparameters:
num_layers: 7
units0: 120
activation0: sigmoid
dropout0: 0.5
optimizer: sgd
units1: 16
activation1: tanh
dropout1: 0.3
units2: 80
activation2: sigmoid
dropout2: 0.1
units3: 72
activation3: tanh
dropout3: 0.2
units4: 8
activation4: tanh
dropout4: 0.1
units5: 120
activation5: tanh
dropout5: 0.4
units6: 72
activation6: tanh
dropout6: 0.4
units7: 40
activation7: sigmoid
dropout7: 0.4
Score: 0.6428571343421936

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 64,
 'activation0': 'tanh',
 'dropout0': 0.7,
 'optimizer': 'rmsprop',
 'units1': 56,
 'activation1': 'tanh',
 'dropout1': 0.5,
 'units2': 64,
 'activation2': 'relu',
 'dropout2': 0.6,
 'units3': 120,
 'activation3': 'tanh',
 'dropout3': 0.4,
 'units4': 48,
 'activation4': 'relu',
 'dropout4': 0.2,
 'units5': 96,
 'activation5': 'tanh',
 'dropout5': 0.8,
 'units6': 88,
 'activation6': 'tanh',
 'dropout6': 0.2,
 'units7': 96,
 'activation7': 'relu',
 'dropout7': 0.9}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 56)             │         3,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 56)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            57 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,273 (16.69 KB)

 Trainable params: 4,273 (16.69 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, y_train,
          batch_size=32,
          epochs=100,
          initial_epoch=6,
          validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7341 - loss: 0.5379 - val_accuracy: 0.7922 - val_loss: 0.4707
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7221 - loss: 0.5404 - val_accuracy: 0.7987 - val_loss: 0.4698
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7666 - loss: 0.4907 - val_accuracy: 0.7857 - val_loss: 0.4669
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7345 - loss: 0.5546 - val_accuracy: 0.7987 - val_loss: 0.4650
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7253 - loss: 0.5314 - val_accuracy: 0.7857 - val_loss: 0.4646
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7457 - loss: 0.5519 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5278 - val_accuracy: 0.7857 - val_loss: 0.4679
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7181 - loss: 0.5323 - val_accuracy: 0.7792 - val_loss: 0.4662
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7427 - loss: 0.5509 - val_accuracy: 0.7857 - val_loss: 0.4648
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7534 - loss: 0.5042 - val_accuracy: 0.7857 - val_loss: 0.4653
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7465 - loss: 0.5479 - val_accuracy: 0.7857 - val_loss: 0.4656
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7459 - loss: 0.5096 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7121 - loss: 0.5586 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7366 - loss: 0.5313 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7582 - loss: 0.4905 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7172 - loss: 0.5386 - val_accuracy: 0.7792 - val_loss: 0.4644
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7556 - loss: 0.5150 - val_accuracy: 0.7792 - val_loss: 0.4621
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7480 - loss: 0.5277 - val_accuracy: 0.7792 - val_loss: 0.4629
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7571 - loss: 0.4841 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7728 - loss: 0.4800 - val_accuracy: 0.7922 - val_loss: 0.4656
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7555 - loss: 0.5063 - val_accuracy: 0.7792 - val_loss: 0.4676
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7532 - loss: 0.5238 - val_accuracy: 0.7922 - val_loss: 0.4671
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7723 - loss: 0.4882 - val_accuracy: 0.7857 - val_loss: 0.4647
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7667 - loss: 0.4786 - val_accuracy: 0.7857 - val_loss: 0.4642
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4765 - val_accuracy: 0.7792 - val_loss: 0.4666
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4871 - val_accuracy: 0.7792 - val_loss: 0.4650
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7368 - loss: 0.5294 - val_accuracy: 0.7727 - val_loss: 0.4673
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7708 - loss: 0.5263 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7600 - loss: 0.5204 - val_accuracy: 0.7857 - val_loss: 0.4635
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7761 - loss: 0.5045 - val_accuracy: 0.7922 - val_loss: 0.4625
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7840 - loss: 0.4621 - val_accuracy: 0.7857 - val_loss: 0.4636
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7625 - loss: 0.4873 - val_accuracy: 0.7922 - val_loss: 0.4632
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7584 - loss: 0.4864 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7908 - loss: 0.4741 - val_accuracy: 0.7922 - val_loss: 0.4646
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7523 - loss: 0.4935 - val_accuracy: 0.7857 - val_loss: 0.4664
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7611 - loss: 0.5041 - val_accuracy: 0.7857 - val_loss: 0.4637
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7641 - loss: 0.5091 - val_accuracy: 0.7792 - val_loss: 0.4636
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7672 - loss: 0.4656 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7847 - loss: 0.4535 - val_accuracy: 0.7857 - val_loss: 0.4628
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7868 - loss: 0.4713 - val_accuracy: 0.7792 - val_loss: 0.4621
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7486 - loss: 0.5328 - val_accuracy: 0.7857 - val_loss: 0.4599
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7531 - loss: 0.4846 - val_accuracy: 0.7857 - val_loss: 0.4608
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7825 - loss: 0.4731 - val_accuracy: 0.7792 - val_loss: 0.4598
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7197 - loss: 0.5175 - val_accuracy: 0.7792 - val_loss: 0.4590
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7643 - loss: 0.5025 - val_accuracy: 0.7727 - val_loss: 0.4596
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7545 - loss: 0.4939 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7391 - loss: 0.5338 - val_accuracy: 0.7792 - val_loss: 0.4600
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7636 - loss: 0.4688 - val_accuracy: 0.7857 - val_loss: 0.4591
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7777 - loss: 0.4829 - val_accuracy: 0.7727 - val_loss: 0.4595
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7878 - loss: 0.4787 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7886 - loss: 0.4891 - val_accuracy: 0.7792 - val_loss: 0.4596
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5179 - val_accuracy: 0.7792 - val_loss: 0.4588
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7666 - loss: 0.4741 - val_accuracy: 0.7792 - val_loss: 0.4595
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7565 - loss: 0.5019 - val_accuracy: 0.7792 - val_loss: 0.4588
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7536 - loss: 0.4950 - val_accuracy: 0.7727 - val_loss: 0.4589
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7616 - loss: 0.5100 - val_accuracy: 0.7857 - val_loss: 0.4590
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7372 - loss: 0.5230 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4699 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7535 - loss: 0.5157 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4635 - val_accuracy: 0.7987 - val_loss: 0.4586
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7887 - loss: 0.4603 - val_accuracy: 0.7857 - val_loss: 0.4603
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7947 - loss: 0.4594 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7685 - loss: 0.5042 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7784 - loss: 0.4721 - val_accuracy: 0.7857 - val_loss: 0.4598
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7694 - loss: 0.4581 - val_accuracy: 0.7857 - val_loss: 0.4595
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7966 - loss: 0.4841 - val_accuracy: 0.7857 - val_loss: 0.4604
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.4788 - val_accuracy: 0.7857 - val_loss: 0.4602
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7630 - loss: 0.5168 - val_accuracy: 0.7857 - val_loss: 0.4608
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7732 - loss: 0.4838 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7367 - loss: 0.5008 - val_accuracy: 0.7857 - val_loss: 0.4603
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7853 - loss: 0.4635 - val_accuracy: 0.7857 - val_loss: 0.4606
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7711 - loss: 0.4795 - val_accuracy: 0.7857 - val_loss: 0.4602
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4816 - val_accuracy: 0.7792 - val_loss: 0.4597
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7480 - loss: 0.5183 - val_accuracy: 0.7857 - val_loss: 0.4596
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7621 - loss: 0.4648 - val_accuracy: 0.7792 - val_loss: 0.4597
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7550 - loss: 0.4991 - val_accuracy: 0.7792 - val_loss: 0.4601
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7601 - loss: 0.4873 - val_accuracy: 0.7857 - val_loss: 0.4599
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7756 - loss: 0.4454 - val_accuracy: 0.7792 - val_loss: 0.4596
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7668 - loss: 0.4787 - val_accuracy: 0.7792 - val_loss: 0.4596
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7943 - loss: 0.4464 - val_accuracy: 0.7857 - val_loss: 0.4610
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7630 - loss: 0.4999 - val_accuracy: 0.7857 - val_loss: 0.4618
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7721 - loss: 0.4695 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7909 - loss: 0.4407 - val_accuracy: 0.7922 - val_loss: 0.4594
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7758 - loss: 0.4773 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7941 - loss: 0.4513 - val_accuracy: 0.7922 - val_loss: 0.4572
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7871 - loss: 0.4365 - val_accuracy: 0.7922 - val_loss: 0.4587
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4633 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7744 - loss: 0.4880 - val_accuracy: 0.7922 - val_loss: 0.4580
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7786 - loss: 0.4739 - val_accuracy: 0.7922 - val_loss: 0.4582
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7693 - loss: 0.4610 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7390 - loss: 0.4988 - val_accuracy: 0.7922 - val_loss: 0.4593
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7831 - loss: 0.4786 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7870 - loss: 0.4512 - val_accuracy: 0.7922 - val_loss: 0.4596
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7910 - loss: 0.4564 - val_accuracy: 0.7922 - val_loss: 0.4595